defaultTag: "Membro"

Tags:
  Dono:
    permission: "tag.dono"
    prefix: "&4&lDONO &4"
  Gerente:
    permission: "tag.gerente"
    prefix: "&4&lGERENTE &4"
  Admin:
    permission: "tag.admin"
    prefix: "&c&lADMIN &c"
  Mod:
    permission: "tag.mod"
    prefix: "&2&lMODERADOR &2"
  Ajudante:
    permission: "tag.ajudante"
    prefix: "&e&lAJUDANTE &e"
  Membro:
    permission: "tag.membro"
    prefix: "&7&lMEMBRO &7"