Tags: #Faça as tags do maior pro menor!
  Dono:
    permission: "tag.dono"
    prefix: "&4&lDONO &4"
    position: a #Prioridade no TAB;
  Gerente:
    permission: "tag.gerente"
    prefix: "&4&lGERENTE &4"
    position: b #Prioridade no TAB;
  Ajudante:
    permission: "tag.ajudante"
    prefix: "&e&lAJUDANTE &e"
    position: c #Prioridade no TAB;
  Membro:
    permission: "tag.membro"
    prefix: "&7&lMEMBRO &7"
    position: d #Prioridade no TAB;